spin_manifest_version = "1"
authors = ["Joel Dice <joel.dice@gmail.com>"]
description = ""
name = "notes"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "notes"
source = "target/wasm32-wasi/release/notes.wasm"
files = [{ source = "client/dist/", destination = "/" }]
key_value_stores = ["default"]
[component.config]
# TODO: Set this to the output of `cargo run --release -p derive-public-key $ORIGIN`, where
# `$ORIGIN` is host you intend to run this app on, e.g. `http://127.0.0.1:3000`:
public_key = "TODO"
[component.trigger]
route = "/..."
[component.build]
command = "(cd client && trunk build --release) && cargo build --target wasm32-wasi --release"
watch = [
  "src/**/*.rs",
  "Cargo.toml",
  "client/src/**/*.rs",
  "client/index.html",
  "client/Cargo.toml"
]
