[package]
name = "derive-public-key"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
ed25519-dalek = "1.0.1"
hex = "0.4.3"
rpassword = "7.2.0"
scrypt = { version = "0.11.0", default-features = false }
